apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql-secret
  namespace: my-app-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: YXV0aF9kYg==
  MYSQL_USER: YXV0aF91c2Vy
  MYSQL_PASSWORD: YXV0aF9wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: order-mysql-secret
  namespace: my-app-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: b3JkZXJfZGI=
  MYSQL_USER: b3JkZXJfdXNlcg==
  MYSQL_PASSWORD: b3JkZXJfcGFzc3dvcmQ=
