apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-service
  namespace: my-app-ns
spec:
  selector:
    app: auth-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: order-mysql-service
  namespace: my-app-ns
spec:
  selector:
    app: order-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
