server:
  host: "0.0.0.0"
  port: 8081

database:
  host: "auth-mysql"
  port: 3306
  username: "auth_user"
  password: "auth_password"
  dbname: "auth_db"

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expiration_time: 24

# prometheus:
#   port: 9091
