# Default values for dependent-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

opensearch:
  enabled: false

db:
  enabled: false

monitoring:
  enabled: false

cert-manager:
  enabled: true